# Generated by Django 3.2.3 on 2021-07-05 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userfollows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfollows',
            name='followed_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='followed_by', to='user.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfollows',
            name='user_to_follow',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='userfollows',
            unique_together={('user', 'followed_user')},
        ),
    ]
